name: crm
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  dio: ^5.4.3+1
  get: ^4.6.6
  flutter_svg: ^2.2.3
  file_picker: ^8.1.2
  table_calendar: ^3.1.2
  shared_preferences: ^2.5.3
  url_launcher: ^6.1.11
  cached_network_image: ^3.4.1
  fl_chart: ^1.1.1
  flutter_screenutil: ^5.9.3

  # JSON serialization
  json_annotation: ^4.9.0
  # Freezed
  freezed_annotation: ^2.3.3
  retrofit: ^4.9.1
  retrofit_generator: ^9.7.0
  bloc: ^9.1.0
  get_it: ^9.2.0
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^9.2.4
  shimmer: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # build_runner for code generation
  build_runner: ^2.5.4
  json_serializable: ^6.6.2
  freezed: ^2.3.6+1

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Alexandria
      fonts:
        - asset: lib/fonts/Alexandria-VariableFont_wght.ttf
    - family: MyFlutterApp
      fonts:
        - asset: lib/fonts/MyFlutterApp.ttf

# flutter_native_splash configuration
flutter_native_splash:
  color: "#ffffff"                  # لون الخلفية
  image: 'images/splash_screen.png' # مسار صورة السبلاتش
  android: true
  ios: true
  android_gravity: fill
  ios_content_mode: scale_to_fill
